### ISSUE TITLE
无法设置壁纸

### ISSUE THREAD

**Issue by neolin0629** [fofolee/uTools-RandomWallpapers#1]
utools版本 v1.0.6-beta
RandomWallpapers版本 v0.0.2
系统版本 windows 10 Pro v1903

壁纸可以下载后再设置，就是直接设置没有效果。

**Comment by fofolee** [comment]
已在0.0.3中修复，等更新

**Comment by neolin0629** [comment]
已经更新并修复了，非常好用，谢谢。
